Add system fields
Kicksaw-Consulting/simple-mockforce pull request #14
Opened 2022-06-01 18:36 UTC by Safintim

Hi! I would like to participate in a project. I am using this library and have run into problems. I will make some pr, do you mind?

This pr for system fields. Every record has system fields, which are listed here https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/system_fields.htm

2022-06-02 15:03 UTC, brno32 requested changes

2022-06-02 15:03 UTC, brno32 commented on simple_mockforce/virtual.py
> +        sobjects = self.get_sobjects(sobject, include_deleted=True)
Shouldn't we only include deleted objects if the query explicitly asks for them? I believe that's SOQL's default behavior

2022-06-02 18:11 UTC, Safintim commented
The test fell because of the use of different timing. I suggest introducing the freezegun library https://github.com/spulec/freezegun. Are you okay with refactoring?

2022-06-02 18:55 UTC, brno32 commented
Yes I'd be okay with using it! I've never used `freezegun`. Do you know how to configure it?

2022-06-03 05:55 UTC, Safintim commented
Yes, it's not hard. I rewrote the test_crud_lifecycle using the `freezegun` library. 

I suggest in the future to work on tests and implement test factories (faker.Factory).

2022-06-03 15:14 UTC, brno32 approved these changes
Thank you so much for this contribution!

2022-06-03 15:14 UTC, merged

2022-06-03 15:17 UTC, brno32 commented
I've released these changes in `0.4.0`